# Copyright (C) 2021 Modoolar <http://www.modoolar.com>
# @author Petar Najman <petar.najman@modoolar.com>
# License LGPLv3.0 or later (https://www.gnu.org/licenses/lgpl-3.0.en.html).
{
    "name": "Infomineo Bootstrap",
    "summary": "Infomineo database bootstrap",
    "category": "Hidden",
    "version": "15.0.0.33.0",
    "license": "LGPL-3",
    "author": "Modoolar",
    "website": "https://modoolar.com",
    "depends": [
        "auditlog",
        "approvals",
        "account_accountant",
        "account_consolidation",
        "documents",
        "sign",
        "web_studio",
        "infomineo_contacts",
        "infomineo_account_asset",
        "infomineo_purchase",
        "infomineo_product",
        "infomineo_sale_subscription",
        "infomineo_hr_expense",
        "infomineo_hr_contract",
        "infomineo_hr_contract_reports",
        "infomineo_hr_holidays",
        "infomineo_hr_holidays_attendance",
        "infomineo_hr_timesheet_attendance",
        "infomineo_hr_skills_attendance",
        "infomineo_hr_payroll",
        "infomineo_hr_payroll_account",
        "infomineo_hr_payroll_holidays",
        "infomineo_project_hr_skills",
        "infomineo_project_planning",
        "infomineo_sale_project",
        "infomineo_project_hr_timesheet",
        "infomineo_sale_project_package_pricing_model",
        "infomineo_sale_timesheet",
        "infomineo_billable_toggle_timesheet_line",
        "infomineo_project_hr",
        "infomineo_timesheet_grid",
        "infomineo_helpdesk",
        "infomineo_commercial_name",
        "hr_timesheet_grid_remove_my_team_filter",
        "hr_holidays_remove_my_team_filter",
        "hr_holidays_group_by_active",
        "hr_holidays_gantt_time_off_type_group_by",
        "hr_work_entry_contract_enterprise",
        "web_grid_view_freeze_first_column",
        "subscription_improvements",
        "approvals_matrix_hr_holidays",
        "approvals_matrix_account",
        "approvals_matrix_sale",
        "approvals_matrix_purchase",
        "approvals_matrix_purchase_requisition",
    ],
}
